#!/usr/bin/bash
#
# Tweet about the last commit in a Git repo.
#
# Requires an application which tweets a string to be in the user's path.
# (my twitterminal does the job)
#

# program which sends tweet
# must tweet argument 1 & be smart about any length checking
twitterer="$HOME/bin/twitterminal"

# GitHub user who 'owns' the repo
github_user="raehik"
# HTTPS because we send them to GitHub to view the commit
short_url_length_https=23

# if we're given an argument, assume it's a git repo and cd to it
# otherwise we'll hope that we're already in a git repo ;)
if [ -n "$1" ]; then
    cd "$1"
fi

# get a ton of info
git_root="$(basename "$(git rev-parse --show-toplevel)")"
last_hash_short="$(git rev-parse --short HEAD)"
last_hash_full="$(git rev-parse HEAD)"
last_message="$(git log -1 --pretty=%s)"
last_author="$(git log -1 --pretty=%aN)"

# check that actually worked
if [ $? -ne 0 ]; then
    echo "${0##*/}: error: Git failed. Are you in a repository, and do you have Git installed?"
    exit 1
fi

# current message w/o URL (shortened by Twitter to 23 chars for HTTPS)
message="\"${last_message}\" - commit $last_hash_short by $last_author @ $github_user/$git_root ()"

# get full message length, adding t.co URL
message_length=$(($(echo -n "$message" | wc -c) + $short_url_length_https))

# if OVER 140 -- exactly 140 is fine
if [ $message_length -gt 140 ]; then
    # count chars in $last_message
    last_message_length=$(echo -n "$last_message " | wc -c)

    # find how many chars we're over by
    chars_over=$(($message_length - 140))

    # set how much of message to keep
    # minus an extra 3 so I can append '...'
    # ...minus another 1 because of zero-based indexing T_T
    chars_to_keep=$(($last_message_length - $chars_over - 3 - 1))

    # re-set $last_message
    last_message="${last_message:0:$chars_to_keep}..."
fi

message_final="\"${last_message}\" - commit $last_hash_short by $last_author @ $github_user/$git_root (https://github.com/$github_user/$git_root/commit/$last_hash_full)"

echo "Tweeting: \"$message_final\""
$twitterer "$message_final"
